include:
  # 1. The Central Dongle (Xiao BLE + Cradio Dongle Shield + Prospector Display)
  - board: xiao_ble//zmk
    shield: cradio_dongle prospector_adapter
  
  # 2. Left Peripheral 
  - board: nice_nano//zmk# e.g., nice_nano_v2 or xiao_ble
    shield: cradio_left
  
  # 3. Right Peripheral
  - board: nice_nano//zmk
    shield: cradio_right
