include:
  # Dongle (Xiao BLE)
  - board: xiao_ble//zmk
    shield: cradio_dongle prospector_adapter
    artifact-name: dongle_xiao
    # This line fixes the 'undeclared' error by defining the old symbol 
    # as the value of the new config (which is 2 for a split keyboard).
    cmake-args: -DCONFIG_ZMK_CPP_FLAGS="-DZMK_SPLIT_BLE_PERIPHERAL_COUNT=CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS"

  # Left Half (nice!nano)
  - board: nice_nano//zmk
    shield: cradio_left
    artifact-name: left_half

  # Right Half (nice!nano)
  - board: nice_nano//zmk
    shield: cradio_right
    artifact-name: right_half
