include:
  # Dongle (Seeed Xiao BLE)
  - board: xiao_ble//zmk
    shield: cradio_dongle prospector_adapter
    artifact-name: dongle_xiao

  # Settings Reset (Flash this to all 3 first if pairing fails)
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: reset_nicenano

  # Left Half (nice!nano v2)
  - board: nice_nano//zmk
    shield: cradio_left
    artifact-name: left_half

  # Right Half (nice!nano v2)
  - board: nice_nano//zmk
    shield: cradio_right
    artifact-name: right_half

