CONFIG_ZMK_DISPLAY=y
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n

CONFIG_PROSPECTOR_STATUS_SCREEN_RADII=n
CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y 
CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=n

CONFIG_PROSPECTOR_ANIMATION_WPM_REFERENCE=200
